# Generated by Django 5.0.3 on 2026-09-29 20:50

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_mobile', '0003_icone_del_menu'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menuicon',
            name='app_label',
            field=models.CharField(help_text="Etichetta dell'app Django (es. `pazienti`, `visite`, `auth`).", max_length=100, verbose_name='App'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='background',
            field=models.CharField(default='#ffffff', help_text='Colore di sfondo del bottone (formato #RRGGBB).', max_length=7, validators=[django.core.validators.RegexValidator(message='Il colore deve essere in formato esadecimale, es. #417690.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Sfondo'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='color',
            field=models.CharField(default='#417690', help_text='Colore del testo / bordo (formato #RRGGBB).', max_length=7, validators=[django.core.validators.RegexValidator(message='Il colore deve essere in formato esadecimale, es. #417690.', regex='^#(?:[0-9a-fA-F]{3}){1,2}$')], verbose_name='Colore'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='icon',
            field=models.CharField(default='📋', help_text='Emoji o carattere unicode da mostrare come icona del bottone.', max_length=16, verbose_name='Icona'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='label_override',
            field=models.CharField(blank=True, help_text='Se valorizzato, sovrascrive il nome mostrato sul bottone.', max_length=100, verbose_name='Nome mostrato'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='model_name',
            field=models.CharField(blank=True, help_text="Nome del modello in minuscolo (es. `paziente`). Lascia vuoto per assegnare l'icona all'intera app.", max_length=100, verbose_name='Modello'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='order',
            field=models.IntegerField(default=0, help_text="Ordinamento crescente all'interno del menu.", verbose_name='Ordine'),
        ),
        migrations.AlterField(
            model_name='menuicon',
            name='visible',
            field=models.BooleanField(default=True, help_text='Se disattivato, la voce non compare nel menu.', verbose_name='Visibile'),
        ),
    ]
