# Generated by Django 5.0.3 on 2026-09-29 20:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_admin_mobile', '0004_nomi_in_italiano'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenuGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(help_text='Come si chiama nel menu, es. «Oggi in studio».', max_length=80, verbose_name='Nome della sezione')),
                ('icona', models.CharField(blank=True, default='', help_text='Facoltativa: compare accanto al nome della sezione.', max_length=16, verbose_name='Icona')),
                ('ordine', models.IntegerField(default=0, help_text='Le sezioni si susseguono da questo numero, dal più piccolo.', verbose_name='Ordine')),
                ('visibile', models.BooleanField(default=True, help_text='Togli la spunta per nascondere la sezione e tutte le sue voci.', verbose_name='Visibile')),
            ],
            options={
                'verbose_name': 'Sezione del menu',
                'verbose_name_plural': 'Sezioni del menu',
                'ordering': ('ordine', 'nome'),
            },
        ),
        migrations.AddField(
            model_name='menuicon',
            name='gruppo',
            field=models.ForeignKey(blank=True, help_text='Lascia vuoto per tenere la voce nella sezione della sua app.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='voci', to='django_admin_mobile.menugroup', verbose_name='Sezione'),
        ),
    ]
